[rule]
description = """
Identifies an unexpected process accessing the password store of commonly used web browsers. Adversaries may steal
credentials from web browsers by reading files specific to the target browser.
"""
id = "f488cd1b-2407-4ec8-8705-7adf99ccbd33"
license = "Elastic License v2"
name = "Web Browser Credential Access via Unusual Process"
os_list = ["windows"]
reference = [
    "https://www.elastic.co/security-labs/globally-distributed-stealers",
    "https://www.elastic.co/security-labs/detect-credential-access",
]
version = "1.0.36"

query = '''
file where event.type == "access" and
 process.executable : "C:\\*" and file.path : ("?:\\Users\\*", "\\??\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy*\\Users\\*") and
 process.thread.Ext.call_stack_summary != null and
 (
  file.name : ("logins.json", "signons.sqlite", "cookies.sqlite") or 
  file.path : 
           ("?:\\Users\\*\\AppData\\Local\\Google\\Chrome\\User Data\\Local State",
            "?:\\Users\\*\\AppData\\Local\\Microsoft\\Edge\\User Data\\Local State", 
            "?:\\users\\*\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Login Data", 
            "?:\\Users\\*\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Login Data", 
            "\\??\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy*\\Users\\*\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Login Data",
            "\\??\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy*\\Users\\*\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Login Data",
            "\\??\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy*\\Users\\*\\AppData\\Local\\Google\\Chrome\\User Data\\Local State",
            "\\??\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy*\\Users\\*\\AppData\\Local\\Microsoft\\Edge\\User Data\\Local State")
  ) and
 (
  process.code_signature.trusted == false or
  process.code_signature.exists == false or
  process.name : ("rundll32.exe", "regsvr32.exe") or
  process.executable :
                ("?:\\Users\\Public\\*",
                 "?:\\Users\\*\\Downloads\\*",
                 "?:\\Windows\\Temp\\*",
                 "?:\\Windows\\Tasks\\*",
                 "?:\\ProgramData\\*",
                 "?:\\Windows\\Microsoft.NET\\*")
  ) and
  not process.code_signature.status : ("errorExpired", "errorCode_endpoint*") and
  not (process.code_signature.trusted == true and
       process.code_signature.subject_name :
              ("Opera Norway AS", "Keeper Security Inc.", "Mozilla Corporation", "Google LLC", "BrowserWorks Ltd", "SAP SE",
               "Emsisoft Ltd", "Galactic Advisors, Inc.", "Dell Technologies Inc.", "Spotify AB", "Fabrice PARISOT",
               "TEAMDEV LTD.", "Gen Digital Inc.", "eClinicalWorks, LLC", "HP Inc.", "AnyDesk Software GmbH",
               "philandro Software GmbH", "NVIDIA Corporation", "Adobe Inc.")) and
  not (process.code_signature.subject_name : "Shift Technologies Inc." and process.code_signature.status : ("errorUntrustedRoot", "errorChaining")) and
  not user.id : ("S-1-5-18", "S-1-5-19", "S-1-5-20") and
  not process.executable : ("?:\\Program Files\\*", "?:\\Program Files (x86)\\*", "C:\\Telivy\\telivy_agent_2.?.?.exe",
                            "?:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\*\\MsMpEng.exe",
                            "?:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\*\\MpCopyAccelerator.exe",
                            "?:\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\Platform\\*\\MsSense.exe",
                            "?:\\ProgramData\\Spillman\\Spillman\\application\\FlexClient\\WebView2\\msedgewebview2.exe",
                            "?:\\ProgramData\\EPSecClient\\*\\EPSecClient_setup.exe",
                            "?:\\ProgramData\\CTES\\Components\\DARAgent\\CSDARAgent.exe",
                            "?:\\ProgramData\\PerfectLaw\\DMS\\WebView2Runtime\\msedgewebview2.exe",
                            "?:\\Users\\*\\AppData\\Local\\Carbonate\\Carbonate\\Application\\Carbonate.exe",
                            "?:\\Users\\*\\Documents\\Chromium\\chrome.exe",
                            "C:\\Telivy\\telivy_agent_2.2.1.exe") and process.pid != 4 and
  not (process.name : "gener8.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\GENER8\\USER DATA\\*") and
  not (process.name : "ccs.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\ENTERPRISEBANKSECUREBROWSER\\USER DATA\\*") and
  not (process.name : "epic.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\EPIC PRIVACY BROWSER\\USER DATA\\*") and
  not (process.name : "ccss?st.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\ESERVISSECUREBROWSER\\USER DATA\\*") and
  not (process.name : "chrome.exe" and 
      file.path : ("?:\\USERS\\*\\APPDATA\\LOCAL\\CHROMIUM\\USER DATA\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\TEMP\\PLAYWRIGHT_CHROMIUMDEV_PROFILE-*\\*")) and
  not file.path : ("?:\\USERS\\*\\APPDATA\\ROAMING\\BURPSUITE\\PRE-WIRED-BROWSER\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\TEMP\\PUPPETEER_DEV_CHROME_PROFILE-*\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\PGADMIN4\\USER DATA\\*",
                   "?:\\USERS\\*\\UNGOOGLED-CHROMIUM-PORTABLE\\DATA\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\TEMP\\PUPPETEER_DEV_CHROME_PROFILE-*\\*",
                   "?:\\Users\\*\\chrome-device\\*",
                   "?:\\Users\\*\\EBWebView\\*",
                   "?:\\Users\\*\\Favorites\\BOOKMARKS\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\ELROND\\MAIAR\\USER DATA\\*",
                   "?:\\Users\\*\\AppData\\Local\\Microsoft\\Edge\\Default BackupDD\\*",
                   "?:\\Users\\*\\Favorites\\bookmarks\\*",
                   "?:\\users\\*\\mayanks\\JxBrowserData\\*",
                   "?:\\Users\\*\\AppData\\Local\\pc_app_store\\User Data\\*",
                   "?:\\Users\\*\\AppData\\Local\\Melvor Idle\\User Data\\*",
                   "?:\\Users\\*\\AppData\\Local\\Streaming\\User Data\\Default\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\BETAFLIGHT-CONFIGURATOR\\USER DATA\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\LEADING\\USER DATA\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\CHROMIUM\\USER DATA\\*",
                   "?:\\Users\\*\\AppData\\Local\\Uniflash\\User Data\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\PGADMIN4\\USER DATA\\*",
                   "?:\\users\\*\\appdata\\local\\Market Axess\\Data\\*\\mayanks\\JxBrowserData\\*",
                   "?:\\Users\\*\\AppData\\Local\\Temp\\flutter_tools.*\\flutter_tools_chrome_device.*\\*",
                   "?:\\Users\\*\\EBWebView\\*",
                   "?:\\Users\\*\\AppData\\Local\\*\\EBWebView\\Snapshots\\*",
                   "?:\\USERS\\*\\APPDATA\\ROAMING\\BURPSUITE\\PRE-WIRED-BROWSER\\SNAPSHOTS\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\WAVEDROMEDITOR\\USER DATA\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\THORIUM\\USER DATA\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\INAV-CONFIGURATOR\\USER DATA\\*",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\TEMP\\PUPPETEER_DEV_PROFILE-*\\*",
                   "?:\\users\\*\\JxBrowserData\\*",
                   "?:\\users\\*\\POPCORN-TIME\\*",
                   "?:\\users\\*\\TIDDLYDESKTOP\\*",
                   "?:\\Users\\*\\LEADING\\*",
                   "?:\\Users\\*chrome_device*") and
  not process.thread.Ext.call_stack_summary like ("ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|acrord32.dll|user32.dll|*",
                                                  "ntdll.dll|appvisvsubsystems64.dll|kernelbase.dll|hmpalert.dll*",
                                                  "ntdll.dll|kernelbase.dll|hmpalert.dll|microsoft.aspnetcore.cryptography.internal.dll*",
                                                  "ntdll.dll|kernelbase.dll|hmpalert.dll|libcef.dll|kernel32.dll|ntdll.dll",
                                                  "ntdll.dll|kernelbase.dll|hmpalert.dll|windows.security.authentication.onlineid.dll|ntdll.dll|kernel32.dll|ntdll.dll",
                                                  "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|mscorlib.ni.dll|Unbacked|clr.dll|mscoreei.dll|mscoree.dll|ntdll.dll",
                                                  "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|hmpalert.dll|*",
                                                  "ntdll.dll|kernelbase.dll|shift.dll|kernel32.dll|ntdll.dll",
                                                  "ntdll.dll|kernelbase.dll|hmpalert.dll|system.security.ni.dll|Unbacked",
                                                  "ntdll.dll|kernelbase.dll|hmpalert.dll|rsaenh.dll|cryptsp.dll|crypt32.dll|cryptuiwizard.dll|cryptui.dll|cryptext.dll|rundll32.exe|kernel32.dll|ntdll.dll",
                                                  "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|browsersettings.dll|kernel32.dll|ntdll.dll",
                                                  "ntdll.dll|apphelp.dll|kernelbase.dll|hmpalert.dll|rsaenh.dll|cryptsp.dll|crypt32.dll|*",
                                                  "ntdll.dll|kernelbase.dll|hmpalert.dll|iertutil.dll|ieframe.dll|user32.dll|ieframe.dll|inetcpl.cpl|*",
                                                  "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|acrord32.dll|*")
'''

min_endpoint_version = "8.7.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1539"
name = "Steal Web Session Cookie"
reference = "https://attack.mitre.org/techniques/T1539/"

[[threat.technique]]
id = "T1555"
name = "Credentials from Password Stores"
reference = "https://attack.mitre.org/techniques/T1555/"
[[threat.technique.subtechnique]]
id = "T1555.003"
name = "Credentials from Web Browsers"
reference = "https://attack.mitre.org/techniques/T1555/003/"



[threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[internal]
min_endpoint_version = "8.7.0"
