[rule]
description = """
Identifies the call of Windows APIs indirectly via a proxy function in verifier.dll. This may be the result of an
evasion attempt to hide the origin of the API call from the call stack such as unbacked memory region.
"""
id = "4564d32d-2f3e-424e-bafd-8fe9972c95ac"
license = "Elastic License v2"
name = "Suspicious Windows API Proxy Call via verifier.dll"
os_list = ["windows"]
reference = [
    "https://blog.cryptoplague.net/main/research/windows-research/proxyalloc-evading-ntallocatevirtualmemory-detection-ft.-elastic-defend-and-binary-ninja",
]
version = "1.0.3"

query = '''
api where 
 (
  (process.thread.Ext.call_stack_final_user_module.name == "verifier.dll" and 
   _arraysearch(process.thread.Ext.call_stack_final_user_module.code_signature, $entry, $entry.subject_name == "Microsoft Windows")) or 

  (process.Ext.api.behaviors == "proxy_call" and 
   process.thread.Ext.call_stack_summary like 
                       ("ntdll.dll|verifier.dll|*",
                        "ntdll.dll|kernelbase.dll|verifier.dll|*", 
                        "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|verifier.dll|*", 
                        "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|verifier.dll|*") and 
   process.thread.Ext.call_stack_final_user_module.name == "Undetermined")
  ) and 

/* exclusions */
not (
 (process.Ext.api.name in ("connect", "IoCreateDevice", "DeviceIoControl")) or
 (process.Ext.api.name == "WriteProcessMemory" and process.Ext.api.summary like "WriteProcessMemory( Self, * )" and
  process.executable like~ "?:\\Windows\\Sys?????\\WerFault.exe" and
  _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info like "c:\\windows\\sys?????\\kernelbase.dll!PssDuplicateSnapshot*"))
) and

not (process.Ext.api.name == "VirtualProtect" and
     process.thread.Ext.call_stack_final_user_module.name == "verifier.dll" and
     process.thread.Ext.call_stack_summary like "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|verifier.dll|dbgmodel.dll|*" and
     _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info like "c:\\windows\\syswow64\\dbgmodel.dll*")) and

not (process.Ext.api.name in ("SuspendThread", "NtSuspendProcess") and
     process.thread.Ext.call_stack_summary like
                          ("wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|dbgcore.dll|verifier.dll|*",
                           "ntdll.dll|kernelbase.dll|verifier.dll|twinapi.appcore.dll|dbgeng.dll|*",
                           "wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|verifier.dll|dbgeng.dll|*",
                           "ntdll.dll|kernelbase.dll|verifier.dll|twinapi.appcore.dll|faultrep.dll|*",
                           "wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|verifier.dll|policymanager.dll|dbgeng.dll|*",
                           "wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|verifier.dll|twinapi.appcore.dll|*",
                           "ntdll.dll|kernelbase.dll|verifier.dll|deploypkg.dll|dbgeng.dll|*",
                           "ntdll.dll|verifier.dll|faultrep.dll|werfault.exe|kernel32.dll|ntdll.dll", 
                           "ntdll.dll|kernelbase.dll|verifier.dll|system.core.ni.dll|powershell.exe|kernel32.dll|ntdll.dll")) and

not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info like
                                     ("c:\\windows\\sys?????\\verifier.dll!VerifierStopMessage*",
                                      "c:\\windows\\sys?????\\verifier.dll!VerifierDisableFaultInjectionExclusionRange*",
                                      "c:\\windows\\sys?????\\verifier.dll!VerifierSetRuntimeFlags*",
                                      "c:\\windows\\sys?????\\verifier.dll+0x*",
                                      "c:\\windows\\sys?????\\ntdll.dll!LdrLoadDll+*",
                                      "c:\\windows\\sys?????\\dxdiagn.dll!DllUnregisterServer*",
                                      "c:\\windows\\syswow64\\d3d10warp.dll!QueryDListForApplication*",
                                      "c:\\windows\\syswow64\\dbgmodel.dll*",
                                      "c:\\windows\\winsxs\\amd64_microsoft*\\wcp.dll!?RtlCaptureTracingParameterList*",
                                      "c:\\program files\\adobe\\adobe creative cloud experience\\js\\node_modules\\adobe-cr\\build\\release\\crclient.dll*")) and

not process.thread.Ext.call_stack_summary like
                       ("ntdll.dll|verifier.dll|kernelbase.dll|*",
                        "ntdll.dll|kernelbase.dll|verifier.dll|jitv.dll|verifier.dll|*",
                        "ntdll.dll|kernelbase.dll|verifier.dll|*|user32.dll|ntdll.dll|win32u.dll|*",
                        "ntdll.dll|kernelbase.dll|verifier.dll|ntdll.dll|kernelbase.dll|combase.dll|*",
                        "ntdll.dll|verifier.dll|clr.dll|verifier.dll|*",
                        "ntdll.dll|kernelbase.dll|verifier.dll|clr.dll|*",
                        "ntdll.dll|kernelbase.dll|verifier.dll|mscoreei.dll|*|combase.dll|*",
                        "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|verifier.dll|clr.dll|*",
                        "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|verifier.dll|systemsettings.datamodel.dll|*",
                        "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|verifier.dll|d3d10warp.dll|*",
                        "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|verifier.dll|dbgmodel.dll|verifier.dll|*",
                        "ntdll.dll|kernelbase.dll|verifier.dll|*|verifier.dll|*|combase.dll|*",
                        "ntdll.dll|verifier.dll|mscoreei.dll|mscoree.dll|ntdll.dll|kernelbase.dll|*",
                        "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|verifier.dll|*|verifier.dll|*",
                        "ntdll.dll|kernelbase.dll|verifier.dll|user32.dll|ntdll.dll|win32u.dll|user32.dll|verifier.dll|kernel32.dll|ntdll.dll")
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1620"
name = "Reflective Code Loading"
reference = "https://attack.mitre.org/techniques/T1620/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
