[rule]
description = """
Identifies Windows Native API calls from an unusual Microsoft signed module. This may be the result of a code injection
using module stomping.
"""
id = "9f25e346-e484-4772-8502-9a769d9a0c0c"
license = "Elastic License v2"
name = "Windows API Call from a Stomped Microsoft Module"
os_list = ["windows"]
version = "1.0.2"

query = '''
api where process.Ext.api.name in ("VirtualAlloc", "VirtualProtect", "WriteProcessMemory", "SetThreadContext", "SuspendThread", "VirtualProtectEx") and
 process.Ext.api.behaviors == "native_api" and
 process.Ext.api.behaviors : ("execute_shellcode", "hollow_image", "HIDDEN_image_hooked", "shellcode", "allocate_shellcode", "execute_shellcode", "unbacked_rwx", "rwx") and
 process.Ext.token.integrity_level_name != "low" and
 process.thread.Ext.call_stack_final_user_module.path : ("c:\\windows\\system32\\*.dll", "c:\\windows\\syswow64\\*.dll") and
 _arraysearch(process.thread.Ext.call_stack_final_user_module.code_signature, $entry,
              $entry.trusted == true and $entry.subject_name : ("Microsoft Corporation", "Microsoft Windows")) and 
 /* trailing bytes in the final user module */
 _arraysearch(process.thread.Ext.call_stack, $entry,
              stringcontains~($entry.symbol_info, process.thread.Ext.call_stack_final_user_module.name) and $entry.allocation_private_bytes >= 10000) and
 not process.thread.Ext.call_stack_final_user_module.protection_provenance : ("kernel", "kernel|*", "ebehmoni.dll", "devicesoftwareinstallationclient.dll", "ifsutil.dll") and 
 not (process.thread.Ext.call_stack_final_user_module.path : "c:\\windows\\system32\\dk2win64.dll" and 
      process.thread.Ext.call_stack_summary : "ntdll.dll|dk2win64.dll|aad.core.dll") and
 not process.thread.Ext.call_stack_final_user_module.path : ("c:\\windows\\syswow64\\apphelp.dll", "c:\\windows\\syswow64\\msvcp140.dll") and
 not (process.executable : "C:\\Windows\\SysWOW64\\dllhost.exe" and
      process.parent.executable : "C:\\Windows\\System32\\svchost.exe" and
      process.command_line : "\"C:\\windows\\SysWOW64\\DllHost.exe\" /Processid:{776DBC8D-7347-478C-8D71-791E12EF49D8}" and
      process.thread.Ext.call_stack_final_user_module.path : "c:\\windows\\syswow64\\*.dll")
'''

min_endpoint_version = "8.10.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
