[rule]
description = "Enumeration of security products may be a precursor to Defense Evasion."
id = "8749c08b-58f5-4e7c-ab15-3551b7541f7a"
license = "Elastic License v2"
name = "Suspicious Security Product Enumeration"
os_list = ["windows"]
version = "1.0.5"

query = '''
api where
  process.Ext.api.name like "IWbemServices::CreateInstanceEnum*" and
  process.Ext.api.parameters.operation in ("AntiVirusProduct", "Win32_DeviceGuard") and
  process.Ext.api.metadata.client_is_local == true and process.parent.executable != null and

  /* ignore process cache enrichment failures */
  process.Ext.api.metadata.client_process_id == null and
  
  /* exclusions */
  not(
   (process.name in ("MpCmdRun.exe", "MsMpEng.exe") and
    process.code_signature.subject_name == "Microsoft Windows Publisher" and process.code_signature.trusted == true and
    process.executable :
           ("?:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\*.exe",
            "?:\\Program Files\\Microsoft Security Client\\*.exe",
            "?:\\Program Files\\Windows Defender\\*.exe",
            "?:\\Program Files (x86)\\Windows Defender\\*.exe") and
    process.parent.executable :
           ("?:\\Windows\\System32\\services.exe",
            "?:\\Windows\\System32\\svchost.exe",
            "?:\\Program Files\\Windows Defender\\MpCmdRun.exe")) or

   (process.executable : ("?:\\Windows\\System32\\MRT.exe", "?:\\$WINDOWS.~BT\\Sources\\SetupHost.exe") and
    process.code_signature.subject_name == "Microsoft Windows" and process.code_signature.trusted == true) or

   (process.executable : ("?:\\$Windows.~??\\Sources\\SetupHost.exe", "?:\\$WINDOWS.~??\\Sources\\mighost.exe") and
    process.code_signature.subject_name == "Microsoft Windows" and process.code_signature.trusted == true) or

   (process.executable : "C:\\Windows\\System32\\svchost.exe" and user.id == "S-1-5-18" and
    process.parent.executable : "?:\\Windows\\System32\\services.exe" and process.command_line like "* -p -s Winmgmt*") or

   (process.executable : "C:\\Program Files (x86)\\Ivanti\\EPM Agent\\Inventory\\ldiscn32.exe" and
    process.code_signature.subject_name == "Ivanti, Inc." and process.code_signature.trusted == true) or

   (process.executable like "C:\\Program Files (x86)\\ASUS\\AsusFanControlService\\*\\AsusFanControlService.exe" and
    process.code_signature.subject_name == "ASUSTeK COMPUTER INC." and process.code_signature.trusted == true) or

   (process.executable :
            ("?:\\Program Files\\GLPI-Agent\\perl\\bin\\glpi-agent.exe",
             "?:\\Windows\\SysWOW64\\EasyResume.exe",
             "?:\\Windows\\SysWOW64\\Lenovo\\PowerMgr\\EasyResume.exe") and
    process.parent.executable : "?:\\Windows\\System32\\services.exe") or

   (process.executable : "?:\\Windows\\System32\\CompatTelRunner.exe" and
    process.parent.executable : ("?:\\Windows\\System32\\CompatTelRunner.exe", "?:\\Windows\\System32\\svchost.exe") and
    process.command_line like ("*-m:appraiser.dll -f:UpdateAvStatus*", "*m:appraiser.dll -f:DoScheduledTelemetryRun*")) or

   (process.executable : "?:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" and process.Ext.api.parameters.operation == "Win32_DeviceGuard" and
    process.parent.executable like "?:\\Program Files\\Microsoft Cloud Managed Desktop Extension\\CMDExtension\\Microsoft.Management.Services.CloudManagedDesktop.Agent.exe") or

   (process.executable : "?:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" and
    process.parent.executable : "?:\\Windows\\System32\\cmd.exe" and user.id == "S-1-5-18" and
    process.Ext.api.parameters.operation == "Win32_DeviceGuard" and
    process.command_line == "Powershell  \"(Get-CimInstance -ClassName Win32_DeviceGuard -Namespace root\\Microsoft\\Windows\\DeviceGuard).SecurityServicesRunning\"") or

   (process.executable : "?:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" and
    process.parent.executable : "?:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" and
    user.id == "S-1-5-18" and process.command_line like "*HexProductState*") or

   (process.executable : "?:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" and
    process.parent.executable : ("?:\\Windows\\explorer.exe", "?:\\Windows\\System32\\cmd.exe", "?:\\Program Files\\Mesh Agent\\MeshAgent.exe") and
    process.command_line in ("powershell",
                             "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                             "\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" ",
                             "\"C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe\" -noexit -command import-module ActiveDirectory")) or

   (process.code_signature.subject_name == "CPUID" and process.code_signature.trusted == true)
  )
'''

min_endpoint_version = "8.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1518"
name = "Software Discovery"
reference = "https://attack.mitre.org/techniques/T1518/"
[[threat.technique.subtechnique]]
id = "T1518.001"
name = "Security Software Discovery"
reference = "https://attack.mitre.org/techniques/T1518/001/"



[threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

[internal]
min_endpoint_version = "8.15.0"
