[rule]
description = "Identifies the download or execution of a file matching PDF Adware patterns."
id = "a0ceeed6-c1fe-45a9-835d-8956037adf7a"
license = "Elastic License v2"
name = "Potential PDF Adware Behavior"
os_list = ["windows"]
version = "1.0.1"

query = '''
any where
(
 (event.category == "file" and event.action == "creation" and file.Ext.windows.zone_identifier >= 3 and
  file.extension : "msi" and file.origin_url regex """https://.*/\?cid=[a-zA-Z0-9]{8,}\&id=[0-9]{8}""") or

 (event.category == "file" and not event.action in ("open", "deletion") and file.name : "onestart.exe" and
  file.path : "C:\\Users\\*\\AppData\\Local\\OneStart.ai\\OneStart\\Application\\onestart.exe") or

 (event.category == "process" and event.action == "start" and
  process.executable : "C:\\Users\\*\\AppData\\Local\\OneStart.ai\\OneStart\\Application\\onestart.exe")
)
'''

min_endpoint_version = "8.15.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1566"
name = "Phishing"
reference = "https://attack.mitre.org/techniques/T1566/"
[[threat.technique.subtechnique]]
id = "T1566.001"
name = "Spearphishing Attachment"
reference = "https://attack.mitre.org/techniques/T1566/001/"

[[threat.technique.subtechnique]]
id = "T1566.002"
name = "Spearphishing Link"
reference = "https://attack.mitre.org/techniques/T1566/002/"



[threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1204"
name = "User Execution"
reference = "https://attack.mitre.org/techniques/T1204/"
[[threat.technique.subtechnique]]
id = "T1204.001"
name = "Malicious Link"
reference = "https://attack.mitre.org/techniques/T1204/001/"

[[threat.technique.subtechnique]]
id = "T1204.002"
name = "Malicious File"
reference = "https://attack.mitre.org/techniques/T1204/002/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1218"
name = "System Binary Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1218/"
[[threat.technique.subtechnique]]
id = "T1218.007"
name = "Msiexec"
reference = "https://attack.mitre.org/techniques/T1218/007/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.15.0"
