[rule]
description = """
Detects the execution of a Windows script with calling the sleep function along with other suspicious features and like
execution or download.
"""
id = "30203e6b-0f9e-410a-a34d-6fe037866cca"
license = "Elastic License v2"
name = "Potential Windows Script Evasion via Sleep"
os_list = ["windows"]
version = "1.0.3"

query = '''
api where process.Ext.api.name == "AmsiScanBuffer" and process.executable != null and

 (process.name in~ ("wscript.exe", "cscript.exe", "mshta.exe", "msxsl.exe") or
  process.Ext.api.parameters.app_name in ("JScript", "VBScript")) and

   /* sleep and execute or download */
   (process.Ext.api.parameters.buffer : ("*IHost.Sleep(*", "*WScript.Sleep*") and
    process.Ext.api.parameters.buffer : ("*.Run(*", "*.ShellExecute(*", "*.responseBody*", "*XMLHTTP*", "*WinHttp*", "*.responseText*")) and

  not process.Ext.api.parameters.content_name :
                     ("?:\\Program Files (x86)\\*",
                      "?:\\Program Files\\*",
                      "C:\\PROGRA~2\\ADVANC~1\\scripts\\ext_*.vbs",
                      "c:\\Windows\\TempInst\\7z*\\DP\\launchquiet_args.vbs",
                      "C:\\Windows\\System32\\*\\sconfig.vbs", 
                      "W:\\Interfaces_*.vbs") and
  not process.parent.executable :
                     ("?:\\Program Files\\HP\\HP LaserJet Pro *\\Bin\\HP LaserJet Pro *.exe",
                      "?:\\Program Files (x86)\\Tanium\\Tanium Client\\TaniumClient.exe",
                      "?:\\Program Files\\System Center Operations Manager\\Gateway\\MonitoringHost.exe",
                      "?:\\Program Files\\Microsoft Monitoring Agent\\Agent\\MonitoringHost.exe",
                      "C:\\ProgramData\\Winget-AutoUpdate\\ServiceUI.exe",
                      "C:\\Windows\\System32\\gpscript.exe") and
  not (process.executable : "C:\\Windows\\LSDeployment\\RemoteDeployment*.exe" and
       process.code_signature.subject_name == "Lansweeper NV" and process.code_signature.trusted == true) and
  not process.executable : ("?:\\Windows\\Sys*\\cscript.exe", "C:\\Windows\\Sys*\\msiexec.exe")
'''

min_endpoint_version = "8.16.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0
tree = true

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.005"
name = "Visual Basic"
reference = "https://attack.mitre.org/techniques/T1059/005/"

[[threat.technique.subtechnique]]
id = "T1059.007"
name = "JavaScript"
reference = "https://attack.mitre.org/techniques/T1059/007/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

[internal]
min_endpoint_version = "8.16.0"
