[rule]
description = """
Identifies the use of the WMI PS_ScheduledTask class methods to create a new scheduled task leveraging the Windows
Management Instrumentation under the hood.
"""
id = "a0f12a20-5201-47f8-a49f-bc80700a3d2c"
license = "Elastic License v2"
name = "Scheduled Task Creation via PowerShell"
os_list = ["windows"]
version = "1.0.1"

query = '''
api where
  process.Ext.api.name == "IWbemServices::ExecMethod" and
   process.Ext.api.parameters.operation : ("*PS_ScheduledTask::Register*", "*PS_ScheduledTask::NewAction*") and

   not process.executable : "C:\\Program Files\\Microsoft Azure Active Directory Connect\\AzureADConnect.exe" and
   not (process.executable : "C:\\Windows\\System32\\WindowsPowerShell\\v?.?\\powershell.exe" and user.id == "S-1-5-18" and
        process.parent.executable :  ("C:\\Windows\\CCM\\*.exe", 
                                      "C:\\Windows\\SoftwareDistribution\\Download\\*.exe", 
                                      "C:\\Program Files (x86)\\*.exe", 
                                      "C:\\Windows\\System32\\msiexec.exe")) and 
   not process.parent.executable : 
                      ("C:\\Program Files (x86)\\Airwatch\\AgentUI\\AWProcessCommands.exe", 
                       "C:\\Windows\\CCM\\OSDRunPowerShellScript.exe", 
                       "C:\\Windows\\System32\\svchost.exe", 
                       "C:\\Windows\\System32\\gpscript.exe", 
                       "C:\\Windows\\TempInst\\is-*.tmp\\dockManagersetup_*.tmp") and 
   not (process.name : "pwsh.exe" and process.command_line : "\"C:\\Program Files\\PowerShell\\?\\pwsh.exe\"") and 
   not (process.executable : "C:\\Windows\\System32\\WindowsPowerShell\\v?.?\\powershell.exe" and 
        process.command_line :
                     ("\"C:\\WINDOWS\\System32\\WindowsPowerShell\\v?.?\\powershell.exe\" -File C:\\WINDOWS\\ccmcache\\*.ps1",
                      "\"C:\\Windows\\System32\\WindowsPowerShell\\v?.?\\powershell.exe\" -NoProfile -executionPolicy bypass -file  \"C:\\Program Files (x86)\\Microsoft Intune Management Extension\\Policies\\Scripts\\*.ps1\" ",
                      " -NoProfile -Noninteractive -ExecutionPolicy Bypass -File \"C:\\Windows\\SystemTemp\\ps*.ps1\" -propFile \"C:\\Windows\\SystemTemp\\msi*",
                      "*npcapwatchdog*C:\\Program Files\\Npcap\\CheckStatus.bat*",
                      "*C:\\Program Files (x86)\\oz-client*",
                      "C:\\WINDOWS\\System32\\WindowsPowerShell\\v?.?\\powershell.exe",
                      "*C:\\Program Files\\Okta\\Okta Verify\\install_scripts\\Add-ScheduledTasks.ps1*", 
                      "*C:\\Program Files\\Remote Help\\RemoteHelpUpdater.exe*",
                      "\"powershell.exe\" -ExecutionPolicy Bypass -windowstyle hidden -File \"C:\\Program Files\\Common Files\\EETI\\TouchModeXML\\RegisterAllUserTask.ps1\"", 
                      "powershell.exe  -ExecutionPolicy Bypass -File \"C:\\Program Files\\Common Files\\EETI\\TouchModeXML\\RunRegisterAllUserTask.ps1\"", 
                      "\"powershell.exe\" -windowstyle hidden -File \"C:\\Program Files\\Common Files\\EETI\\TouchModeXML\\RegisterAllUserTask.ps1\"", 
                      "*C:\\Program Files\\Microsoft Azure AD Connect Health Agent\\Modules\\AdHealthConfiguration\\AdHealthConfiguration.psd1*",
                      "powershell.exe -ExecutionPolicy AllSigned -WindowStyle Hidden -NonInteractive -File \"C:\\Users\\*\\AppData\\Local\\Temp\\ns*.tmp\\npcapwatchdog.ps1\" -Instdir \"C:\\Program Files\\Npcap\"")) and
   not (process.executable : "C:\\Windows\\System32\\svchost.exe" and
        process.command_line in~ ("C:\\Windows\\system32\\svchost.exe -k netsvcs -p -s Winmgmt") and
        process.parent.executable : "C:\\Windows\\System32\\services.exe")
'''

min_endpoint_version = "8.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1047"
name = "Windows Management Instrumentation"
reference = "https://attack.mitre.org/techniques/T1047/"

[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"
reference = "https://attack.mitre.org/techniques/T1059/001/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1053"
name = "Scheduled Task/Job"
reference = "https://attack.mitre.org/techniques/T1053/"
[[threat.technique.subtechnique]]
id = "T1053.005"
name = "Scheduled Task"
reference = "https://attack.mitre.org/techniques/T1053/005/"



[threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"

[internal]
min_endpoint_version = "8.15.0"
