[rule]
description = """
Identifies interactive logon attempt with alternate credentials and by an unusual process. Adversaries may create a new
token to escalate privileges and bypass access controls.
"""
id = "1ee7b771-28d6-4bf5-a227-d1c8bf04df96"
license = "Elastic License v2"
name = "Interactive Logon by a Suspicious Process"
os_list = ["windows"]
reference = ["https://attack.mitre.org/techniques/T1134/002/"]
version = "1.0.6"

query = '''
authentication where event.action == "log_on" and event.code == "4624" and
 process.Ext.session_info.logon_type == "Interactive" and process.executable : "C:\\*" and
 user.id like ("S-1-5-21*", "S-1-12-*") and (user.effective.id != null and user.effective.id like ("S-1-5-21*", "S-1-12-*")) and
 not (process.code_signature.trusted == true and
      process.code_signature.subject_name in
           ("TeamViewer", "TeamViewer GmbH", "TeamViewer Germany GmbH", "LogMeIn, Inc.", "Siemens AG",
            "QlikTech International AB", "Bomgar Corporation", "NinjaOne LLC", "Island Technology Inc.", "CA, Inc.",
            "CAS Software AG", "Imprivata, Inc.", "Google LLC", "NoMachine S.a.r.l.", "Imprivata, Inc", "Laserfiche",
            "COC COC COMPANY LIMITED", "Given Imaging Ltd", "Luis Cobian Dorta", "Brave Software, Inc.", "CyberArk Software Ltd.",
            "Kofax, Inc.", "Education Management Solutions LLC", "Seagull Scientific, Inc", "Ivanti, Inc.", "Opera Norway AS",
            "PDQ.com Corporation", "itelio GmbH", "Mozilla Corporation", "Vivaldi Technologies AS", "GoTo Technologies USA, LLC",
            "Devolutions Inc", "Seagull Scientific Inc.", "Senior Sistemas S/A", "Rsupport Co., Ltd.", "Redwood Software, Inc.",
            "CA Software Österreich GmbH", "ECI Software Solutions, Inc.", "ISL Online Ltd.", "DATEV eG", "Connectwise, LLC",
            "Shift Technologies Inc.", "YANDEX LLC", "Apollo Technologies Inc.", "Mobatek")) and
 not process.executable :
            ("C:\\Windows\\System32\\winlogon.exe",
             "C:\\Windows\\System32\\wininit.exe",
             "C:\\Windows\\System32\\lsass.exe",
             "C:\\Windows\\System32\\RuntimeBroker.exe",
             "C:\\Windows\\explorer.exe",
             "C:\\Windows\\System32\\ServerManager.exe",
             "C:\\Windows\\System32\\svchost.exe",
             "C:\\Windows\\System32\\wsmprovhost.exe",
             "C:\\Windows\\System32\\CredentialEnrollmentManager.exe",
             "C:\\Windows\\System32\\CredentialUIBroker.exe",
             "C:\\Users\\*\\AppData\\Local\\Apps\\2.0\\*\\*.exe",
             "C:\\Users\\*\\AppData\\Local\\Temp\\SPMigrationAgentSetup*\\SPMigrationAgentSetup\\Microsoft.SharePoint.Migration.ClientInstaller.exe",
             "C:\\Windows\\System32\\oobe\\UserOOBEBroker.exe",
             "C:\\SQL Beacon\\SQL Beacon Agent Gen?\\SQLBeaconAgentUserInterfaceGen?.exe",
             "C:\\Projekte\\Gmos.InfozentraleMain\\Gmos.Infozentrale.WebApi\\bin\\Debug\\net8.0\\Gmos.Infozentrale.WebApi.exe",
             "C:\\Windows\\SysWOW64\\inetsrv\\w3wp.exe",
             "C:\\Windows\\System32\\inetsrv\\w3wp.exe",
             "C:\\Windows\\SysWOW64\\msiexec.exe",
             "C:\\Windows\\System32\\msiexec.exe",
             "C:\\Windows\\ImmersiveControlPanel\\SystemSettings.exe",
             "C:\\Windows\\System32\\CredentialUIBroker.exe",
             "C:\\Windows\\System32\\UserAccountBroker.exe",
             "C:\\Windows\\System32\\mmc.exe",
             "C:\\Program Files (x86)\\KIC H\\KIC.exe",
             "C:\\Windows\\System32\\CloudExperienceHostBroker.exe",
             "C:\\Bruker\\TopSpin4.2.0\\prog\\mod\\xwish3.exe",
             "C:\\Windows\\System32\\Autologon64.exe",
             "C:\\Program Files\\*.exe",
             "C:\\Program Files (x86)\\*.exe")
'''

min_endpoint_version = "8.15.1"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1134"
name = "Access Token Manipulation"
reference = "https://attack.mitre.org/techniques/T1134/"
[[threat.technique.subtechnique]]
id = "T1134.001"
name = "Token Impersonation/Theft"
reference = "https://attack.mitre.org/techniques/T1134/001/"

[[threat.technique.subtechnique]]
id = "T1134.002"
name = "Create Process with Token"
reference = "https://attack.mitre.org/techniques/T1134/002/"



[threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"

[internal]
min_endpoint_version = "8.15.1"
