[rule]
description = """
Detects a package service (npm, pypi) or a script (Python, Ruby, Node) making a direct network request to a known public
IP address lookup web service. Malware tends to perform this action to assess potential targets.
"""
id = "0373350d-05e3-4273-93fa-013e17966ef6"
license = "Elastic License v2"
name = "External IP address discovery via Package or Script"
os_list = ["macos"]
version = "1.0.5"

query = '''
sequence by process.entity_id with maxspan=30s
[process where event.type == "start" and event.action == "exec" and process.name like~ ("python*", "ruby*", "node", "npm", "gems*")]
[network where event.type == "start" and
  destination.domain like~ 
         (
          "*ip-api.com*",
          "*checkip.dyndns.org*",
          "*api.ipify.org*",
          "*api.npoint.io*",
          "*whatismyip.akamai.com*",
          "*bot.whatismyipaddress.com*",
          "*ifcfg.me*",
          "*inet-ip.info*",
          "*ifconfig.me*",
          "*ident.me*",
          "*ipof.in*",
          "*ip.tyk.nu*",
          "*ipwhois.app*",
          "*freeipapi.com*",
          "*icanhazip.com*",
          "*curlmyip.com*",
          "*wgetip.com*",
          "*eth0.me*",
          "*ipecho.net*",
          "*ip.appspot.com*",
          "*api.myip.com*",
          "*geoiptool.com*",
          "*api.2ip.ua*",
          "*api.ip.sb*",
          "*ipinfo.io*",
          "*checkip.amazonaws.com*",
          "*wtfismyip.com*",
          "*iplogger.*",
          "*freegeoip.net*",
          "*freegeoip.app*",
          "*ipinfo.io*",
          "*myip.ipip.net*",
          "*geoplugin.net*",
          "*myip.dnsomatic.com*",
          "*www.geoplugin.net*",
          "*api64.ipify.org*",
          "*ip4.seeip.org*",
          "*.geojs.io*",
          "*portmap.io*",
          "*api.2ip.ua*",
          "*api.db-ip.com*",
          "*geolocation-db.com*",
          "*httpbin.org*",
          "*myip.opendns.com*"
         )]
'''

min_endpoint_version = "8.16.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1016"
name = "System Network Configuration Discovery"
reference = "https://attack.mitre.org/techniques/T1016/"


[threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

[internal]
min_endpoint_version = "8.16.0"
