[rule]
description = """
Detects potential curl CVE-2023-38545 exploitation by monitoring for vulnerable command line arguments in conjunction
with an unusual command line length. A flaw in curl version <= 8.3 makes curl vulnerable to overflow a heap based buffer
in the SOCKS5 proxy handshake. Upgrade to curl version >= 8.4 to patch this vulnerability.
"""
id = "0c188a15-30f5-445c-8655-95c7f93ace88"
license = "Elastic License v2"
name = "Potential curl CVE-2023-38545 Exploitation"
os_list = ["linux"]
reference = [
    "https://curl.se/docs/CVE-2023-38545.html",
    "https://daniel.haxx.se/blog/2023/10/11/curl-8-4-0/",
    "https://twitter.com/_JohnHammond/status/1711986412554531015",
]
version = "1.0.3"

query = '''
process where event.type == "start" and event.action == "exec" and process.name == "curl" 
and (
  process.args : ("--socks5-hostname", "--proxy", "--preproxy", "socks5*") or 
  process.env_vars: ("http_proxy=socks5h://*", "HTTPS_PROXY=socks5h://*", "ALL_PROXY=socks5h://*")
) and length(process.command_line) > 255
'''

min_endpoint_version = "8.6.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1203"
name = "Exploitation for Client Execution"
reference = "https://attack.mitre.org/techniques/T1203/"


[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

[internal]
min_endpoint_version = "8.6.0"
