[rule]
description = """
Identifies the execution of a Linux shell process from a Java JAR application post an incoming network connection. This
behavior may indicate reverse shell activity via a Java application.
"""
id = "e0db3577-879e-4ac2-bd58-691e1343afca"
license = "Elastic License v2"
name = "Potential Linux Reverse Shell via Java"
os_list = ["linux"]
version = "1.0.8"

query = '''
sequence with maxspan=5s
  [network where event.action in ("connection_accepted", "connection_attempted") and process.executable : (
     "/usr/bin/java", "/bin/java", "/usr/lib/jvm/*", "/usr/java/*"
   )] by process.entity_id
  [process where event.action == "exec" and process.parent.executable : (
     "/usr/bin/java", "/bin/java", "/usr/lib/jvm/*", "/usr/java/*"
   ) and process.parent.args : "-jar"  and process.executable : "*sh"] by process.parent.entity_id
'''

min_endpoint_version = "8.7.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"


[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.7.0"
