[rule]
description = """
Detects the use of curl to upload an archived file to an internet server. Threat actors often will collect data on a
system and compress it in an archive file before exfiltrating the file back to their C2 server for review. Many threat
actors have been seen utilizing curl to upload this archive file with the collected data to do this. Use of curl in this
way while not inherently malicious should be considered highly abnormal and suspicious activity.
"""
id = "ea97874d-a232-44b4-a99f-be7850977cd7"
license = "Elastic License v2"
name = "Potential Data Exfiltration Through Curl"
os_list = ["linux"]
reference = ["https://everything.curl.dev/usingcurl/uploads"]
version = "1.0.5"

query = '''
process where event.type == "start" and event.action == "exec" and process.name == "curl" and
process.parent.executable != null and (process.args in ("-F", "-T", "-d") or process.args like "--data*") and 
process.command_line like ("*@/*.zip*", "*@/*.gz*", "*@/*.tgz*", "*b64=@*", "*=<*") and
process.command_line like "*http*" and not (
  process.parent.name in ("bash", "dash", "sh", "tcsh", "csh", "zsh", "ksh", "fish", "flock") or
  process.parent.executable like "/var/lib/docker/*" or
  process.parent.executable in (
    "/usr/sbin/crond", "/usr/share/untangle/bin/configuration-backup-upload-backup.sh", "/usr/local/sbin/haproxy"
  ) or 
  process.command_line like (
    "*http://127.0.0.1*", 
    "*https://127.0.0.1*", 
    "*http://localhost*", 
    "*https://localhost*", 
    "*https://*cloud.es.io*",
    "*@/exec-result.json", 
    "*https://storage.googleapis.com/detonate-prod/*",
    "*https://storage.googleapis.com/detonate-ci/*",
    "*https://*elastic-cloud.com*"
  ) or
  process.parent.name == "ula_check.sh" or
  process.parent.args in (
    "/usr/lib/bats/bats-exec-test", "/opt/error_monitor/error_monitor.sh", "/var/cartenz/send_notify.sh"
  ) or
  process.parent.command_line == "runc init"
)
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1048"
name = "Exfiltration Over Alternative Protocol"
reference = "https://attack.mitre.org/techniques/T1048/"


[threat.tactic]
id = "TA0010"
name = "Exfiltration"
reference = "https://attack.mitre.org/tactics/TA0010/"

[internal]
min_endpoint_version = "7.15.0"
