[rule]
description = """
This rule detects SSH session Id change followed by a suspicious SSHD child process, this may indicate the successful
execution of a potentially malicious process through the Pluggable Authentication Module (PAM) utility. PAM is a
framework used by Linux systems to authenticate users. Adversaries may create malicious PAM modules that grant them
persistence onto the target every time a user logs in by executing a backdoor script or command.
"""
id = "b8bb0b6a-eb7e-4819-9c7e-4e3845b82b91"
license = "Elastic License v2"
name = "Potential Backdoor Execution Through PAM_EXEC"
os_list = ["linux"]
reference = ["https://www.group-ib.com/blog/pluggable-authentication-module/"]
version = "1.0.4"

query = '''
sequence by process.entity_id with maxspan=3s
  [process where event.type == "change" and event.action == "session_id_change" and process.name in ("ssh", "sshd")]
  [process where event.type == "start" and event.action == "exec" and process.parent.name in ("ssh", "sshd") and
   process.args_count == 2 and (
     process.name like ("perl*", "python*", "php*", "ruby*", "lua*") or
     process.executable like ("/tmp/*", "/var/tmp/*", "/dev/shm/*", "./*", "/boot/*") or
     process.name like ".*"
   ) and not (
     process.executable like (
       "/tmp/newroot/*", "/tmp/*ansible-new-dispatch-script.tmp.sh", "/tmp/CVU_*", "/mcp/images/overlay2/*",
        "./.ssh/cmds/ssh_fresh_postfix_from_admindb.pl", "/home/*/pp-ch-dataload/venv/bin/python3",
        "/tmp/*ezyness-testbed-vpn-dispatch-script.tmp.sh", "/tmp/tempRACTrans*", "/tmp/*-infra-openvpn-pcc4-dispatch-script.tmp.sh",
        "/home/*/arreios_server/ve/bin/python", "/tmp/*dispatch-script.tmp.sh", "/tmp/terraform_*.sh",
        "/var/tmp/foreman-ssh-cmd-*/script", "/tmp/cpp/run_script_correo_factu_biller.sh", "/tmp/cpp/run_script_correo_mapeo_inval.sh",
        "/home/*/.venvs/basal/bin/python", "./*/scripts/post_deploy.sh"
     ) or
     process.command_line in ("python --version", "perl /usr/local/bin/ew", "ruby --version", "/usr/bin/perl -v") or
     process.command_line like~ ("/home/*/.venvs/basal/bin/python -V", "perl /home/*/seti/alertas/usofs.pl") or
     process.args like~ "/home/*/checkouts/workers.unet.nl/stop_workers"
   )
  ]
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 1

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1543"
name = "Create or Modify System Process"
reference = "https://attack.mitre.org/techniques/T1543/"


[threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1556"
name = "Modify Authentication Process"
reference = "https://attack.mitre.org/techniques/T1556/"


[threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[internal]
min_endpoint_version = "7.15.0"
